version: '3'
services:
  appcontainer:
    build:
      context: .
      args:
        JAR_FILE: /mufg-jms-transmution-service-1.0.0.jar
    ports:
    - "4000:8080"
  activemqcontainer:
    image: "rmohr/activemq"
    ports:
    - "8161:8161"
