//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 10:02:51 AM WET 
//


package com.mufg.us.amh.vln_ced_401.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mufg.y73.usa.DEP_IRIS.model.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mufg.y73.usa.DEP_IRIS.model.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputDocument }
     * 
     */
    public InputDocument createDocument() {
        return new InputDocument();
    }

    /**
     * Create an instance of {@link InputDocument.AREAGRP }
     * 
     */
    public InputDocument.AREAGRP createDocumentAREAGRP() {
        return new InputDocument.AREAGRP();
    }

    /**
     * Create an instance of {@link InputDocument.AREAGRP.AREA }
     * 
     */
    public InputDocument.AREAGRP.AREA createDocumentAREAGRPAREA() {
        return new InputDocument.AREAGRP.AREA();
    }

    /**
     * Create an instance of {@link InputDocument.AREAGRP.AREA.REC }
     * 
     */
    public InputDocument.AREAGRP.AREA.REC createDocumentAREAGRPAREAREC() {
        return new InputDocument.AREAGRP.AREA.REC();
    }

    /**
     * Create an instance of {@link InputDocument.AREA }
     * 
     */
    public InputDocument.AREA createDocumentAREA() {
        return new InputDocument.AREA();
    }

    /**
     * Create an instance of {@link InputDocument.AREA.REC }
     * 
     */
    public InputDocument.AREA.REC createDocumentAREAREC() {
        return new InputDocument.AREA.REC();
    }

    /**
     * Create an instance of {@link InputDocument.AREAGRP.AREA.REC.FLD }
     * 
     */
    public InputDocument.AREAGRP.AREA.REC.FLD createDocumentAREAGRPAREARECFLD() {
        return new InputDocument.AREAGRP.AREA.REC.FLD();
    }

    /**
     * Create an instance of {@link InputDocument.AREA.REC.FLD }
     * 
     */
    public InputDocument.AREA.REC.FLD createDocumentAREARECFLD() {
        return new InputDocument.AREA.REC.FLD();
    }

}
