spring:
  application:
    name: t36_cbh_505_503_sod_eod
  profiles:
    active: dev
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    pool:
      enabled: true
      max-connections: 10
  vlnced401inputQname: VLN.CED_401.REQ.IN
  vlnced401outputQname: VLN.CED_401.RES.OUT

info:
  app:
    name: CAN_LOAN_IRIS
    version: 1.0.0

api:
  message:
     ccisd: 1208
     encoding: 546
  
---
#===== DEV =======
spring:
  profiles: dev
  
---
#===== TEST =======
spring:
  profiles: test
  activemq:
    broker-url: ${AMQ_BROKER_URL}
    pool:
      enabled: true
      max-connections: 10
  vlnced401inputQname: ${VLN.CED_401_INPUT_QNAME}
  vlnced401outputQname: ${VLN.CED_401_OUTPUT_QNAME}
  

---
#===== MODEL =======
spring:
  profiles: model


---
#===== PROD =======
spring:
  profiles: prod

  
  
server:
  port: 8052


caniris:
  queue:
    vdpced401:
      input: DEP_IRIS.VDP_CED_1301.DBCRB.REQ.IN
      output: DEP_IRIS.VDP_CED_1301.DBCRB.REQ.OUT.AL
      fail: DEP_IRIS.VDP_CED_1301.DBCRB.REQ.IN.FAIL
      exception : DEP_IRIS.VDP_CED_1301.DBCRB.REQ.EXCEPTION
    vdpced402:
      input: DEP_IRIS.VDP_CED_1302.DBCRB.REQ.IN
      output: DEP_IRIS.VDP_CED_1302.DBCRB.REQ.OUT.AL
      fail: DEP_IRIS.VDP_CED_1302.DBCRB.REQ.IN.FAIL
      exception : DEP_IRIS.VDP_CED_1302.DBCRB.REQ.EXCEPTION
    
  