//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:06:39 PM IST 
//


package com.mufg.us.amh.vln_ced_401.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mufg.y73.usa.DEP_IRIS.model.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mufg.y73.usa.DEP_IRIS.model.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.AREAGRP }
     * 
     */
    public Document.AREAGRP createDocumentAREAGRP() {
        return new Document.AREAGRP();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.Body }
     * 
     */
    public Document.AREAGRP.Body createDocumentAREAGRPBody() {
        return new Document.AREAGRP.Body();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.Body.FILE }
     * 
     */
    public Document.AREAGRP.Body.FILE createDocumentAREAGRPBodyFILE() {
        return new Document.AREAGRP.Body.FILE();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.Body.FILE.REC }
     * 
     */
    public Document.AREAGRP.Body.FILE.REC createDocumentAREAGRPBodyFILEREC() {
        return new Document.AREAGRP.Body.FILE.REC();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.SearchKey }
     * 
     */
    public Document.AREAGRP.SearchKey createDocumentAREAGRPSearchKey() {
        return new Document.AREAGRP.SearchKey();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.CustomerHeader }
     * 
     */
    public Document.AREAGRP.CustomerHeader createDocumentAREAGRPCustomerHeader() {
        return new Document.AREAGRP.CustomerHeader();
    }

    /**
     * Create an instance of {@link Document.FileHeader }
     * 
     */
    public Document.FileHeader createDocumentFileHeader() {
        return new Document.FileHeader();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.Body.FILE.REC.FLD }
     * 
     */
    public Document.AREAGRP.Body.FILE.REC.FLD createDocumentAREAGRPBodyFILERECFLD() {
        return new Document.AREAGRP.Body.FILE.REC.FLD();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.SearchKey.SearchFields }
     * 
     */
    public Document.AREAGRP.SearchKey.SearchFields createDocumentAREAGRPSearchKeySearchFields() {
        return new Document.AREAGRP.SearchKey.SearchFields();
    }

    /**
     * Create an instance of {@link Document.AREAGRP.CustomerHeader.ContactDetails }
     * 
     */
    public Document.AREAGRP.CustomerHeader.ContactDetails createDocumentAREAGRPCustomerHeaderContactDetails() {
        return new Document.AREAGRP.CustomerHeader.ContactDetails();
    }

    /**
     * Create an instance of {@link Document.FileHeader.Information }
     * 
     */
    public Document.FileHeader.Information createDocumentFileHeaderInformation() {
        return new Document.FileHeader.Information();
    }

}
